package authhttp

import (
	"errors"
	"fmt"
	"net/http"
	"net/url"
)

// ErrUnsafeTransport marks a refusal to use an endpoint or transport, as
// opposed to a failure to reach one. Every error generated by this package's own
// policy wraps it, malformed-URL errors included: an endpoint that will not
// parse is a refusal in the same sense, since no amount of retrying repairs it.
// Keep that property when adding errors here — an unwrapped one silently reads
// to callers as "transient", which is the opposite of what it means.
//
// Deliberately excluded: an error from a caller's own CheckRedirect, which
// RefuseTransportDowngrade delegates to and returns unchanged. That verdict
// belongs to the caller — we do not know whether retrying it could help, and
// stamping our sentinel on it would report someone else's policy as ours.
// Callers keying on the sentinel therefore see their own errors unchanged,
// which is what lets them tell the two apart.
//
// Callers key on it to decide whether a retry could help: it never can. A
// credential that could not be refreshed because the token endpoint was
// downgraded will not be obtained by authenticating again — the endpoint is
// still downgraded. Distinguishing this from an ordinary network or
// expired-credential failure keeps a client from escalating a configuration
// problem into a user-facing login prompt that is guaranteed to fail.
//
// It survives net/http wrapping: a CheckRedirect error is returned inside a
// *url.Error, which unwraps, so errors.Is reaches this through the client.
var ErrUnsafeTransport = errors.New("unsafe auth transport")

// maxAuthRedirects mirrors the cap Go's default CheckRedirect applies. Setting
// our own CheckRedirect replaces that default, so the bound has to be restated
// here or the chain would be unbounded.
const maxAuthRedirects = 10

// RefuseTransportDowngrade returns a shallow copy of base whose redirect policy
// refuses to leave https. The copy matters: the caller's client is shared with
// other auth traffic and must not acquire this policy as a side effect.
//
// It guards every auth fetch, not only metadata: JWKS on the server, and the
// refresh grant and code exchange on the client. The latter two carry
// credentials in the request body, and a 307 or 308 preserves that body across
// a redirect, so a downgrade there discloses a refresh token or authorization
// code rather than merely weakening a fetch of public material.
//
// The guard *layers on top of* any policy the caller already set rather than
// replacing it — a caller that rejects cross-host redirects, or all redirects,
// must not start following them just because it was passed here. The composed
// policy is therefore the caller's AND ours, which can only ever be more
// restrictive than either alone. The redirect cap is applied unconditionally
// for the same reason: auth metadata fetching stays bounded even if the
// caller's own policy has no ceiling.
func RefuseTransportDowngrade(base *http.Client) *http.Client {
	guarded := *base
	inherited := base.CheckRedirect
	guarded.CheckRedirect = func(req *http.Request, via []*http.Request) error {
		if len(via) >= maxAuthRedirects {
			// Wraps the sentinel like every other refusal here: hitting the
			// cap is us declining to continue, not the issuer being
			// unreachable, and re-authenticating would walk the same chain.
			return fmt.Errorf("stopped after %d redirects: %w", maxAuthRedirects, ErrUnsafeTransport)
		}
		if via[0].URL.Scheme == "https" && req.URL.Scheme != "https" {
			return fmt.Errorf("refusing redirect from https to %s://%s: transport downgrade on the auth path: %w",
				req.URL.Scheme, req.URL.Host, ErrUnsafeTransport)
		}
		if inherited != nil {
			return inherited(req, via)
		}
		return nil
	}
	return &guarded
}

// CheckEndpointURL validates an endpoint named by a metadata document before it
// is used. label identifies the field for the error message ("jwks_uri",
// "token_endpoint", "authorization_endpoint").
//
// This is an absolute requirement, unlike CheckNoSchemeDowngrade, which is
// relative to how the metadata itself arrived. The two are not
// interchangeable: over an http metadata source the downgrade check passes
// *everything*, so without this a document could name a file:// or custom-scheme
// endpoint. That matters most for authorization_endpoint, which is handed to the
// OS URL dispatcher — see the comment in client/browser_other.go.
//
// A scheme test alone is not enough, and neither is url.URL.IsAbs: "https:x"
// parses with Scheme "https" and IsAbs true, but has no host and carries its
// content in Opaque. Requiring a host and an empty Opaque is what actually
// pins this to a real network endpoint.
func CheckEndpointURL(label, rawURL string) error {
	if rawURL == "" {
		return fmt.Errorf("issuer metadata did not advertise %s: %w", label, ErrUnsafeTransport)
	}
	u, err := url.Parse(rawURL)
	if err != nil {
		return fmt.Errorf("%s %q is not a valid URL (%v): %w", label, rawURL, err, ErrUnsafeTransport)
	}
	switch u.Scheme {
	case "http", "https":
	default:
		return fmt.Errorf("%s %q uses unsupported scheme %q; only http and https endpoints are accepted: %w",
			label, rawURL, u.Scheme, ErrUnsafeTransport)
	}
	if u.Opaque != "" || u.Host == "" {
		return fmt.Errorf("%s %q is not an absolute URL with a host: %w", label, rawURL, ErrUnsafeTransport)
	}
	return nil
}

// CheckNoSchemeDowngrade rejects a resolved endpoint that is less protected
// than the document that named it. label identifies the field for the error
// message.
//
// Judged against the scheme the metadata itself arrived over rather than an
// absolute https requirement: if the document already travelled in clear text
// there is no downgrade left to prevent, and that case is the local development
// setup the config layer gates behind --insecure-oidc-issuer. Pair it with
// CheckEndpointURL, which does not have that escape.
func CheckNoSchemeDowngrade(label, sourceURL, resolvedURL string) error {
	source, err := url.Parse(sourceURL)
	if err != nil {
		return fmt.Errorf("parse metadata source %q (%v): %w", sourceURL, err, ErrUnsafeTransport)
	}
	resolved, err := url.Parse(resolvedURL)
	if err != nil {
		return fmt.Errorf("parse %s %q (%v): %w", label, resolvedURL, err, ErrUnsafeTransport)
	}
	if source.Scheme == "https" && resolved.Scheme != "https" {
		return fmt.Errorf("issuer metadata fetched over https advertised a non-https %s %q; refusing to use a downgraded endpoint: %w",
			label, resolvedURL, ErrUnsafeTransport)
	}
	return nil
}
